<?php

namespace Wynajem\BlogBundle\Repository;



/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends TaxonomyRepository
{


    public function getTagsListOcc()
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.slug, t.name, COUNT(p) as occ')
            ->leftJoin('t.posts','p')
            ->groupBy('t.name');

        return $qb->getQuery()->getArrayResult();
    }


}
