services:
    user_mailer:
        class: Common\UserBundle\Mailer\UserMailer
        arguments: [@mailer, "bliksem031@gmail.com", "Wynajem Admin"]

    user_manager:
        class: Common\UserBundle\Manager\UserManager
        arguments: [@doctrine, @router, @templating, @security.encoder_factory, @user_mailer]